### ISSUE TITLE
Add the ability to provide information on issue contributors, so they are linked

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/generate-release-notes#41]
## Background
Some contributors are not mapped.

## Feature
Add the ability to provide information on issue contributors, so they are linked
.
## Proposed Solution [Optional]
Solution Ideas:
Have a mapping in configuration:
author1 name->github handle X
author2 name->github handle Y

**Comment by miroslavpojer** [comment]
A better solution would be to have a public email in the GH account than this. Otherwise, I can imagine that this could help.

**Comment by benedeki** [comment]
Actually, it's a general map, to replace any text. Very useful to auto-add some things - like links to commonly referred projects.

**Comment by benedeki** [comment]
> A better solution would be to have a public email in the GH account than this. Otherwise, I can imagine that this could help.

Not sure, if enforcing public email is a user-friendly solution.

**Comment by miroslavpojer** [comment]
Duplicate to #97.
