### ISSUE TITLE
Seems some tickets were not picked up

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/generate-release-notes#42]
## Describe the bug
Seems some issues nor PR were picked up by the script in Atum project (release 0.2)

## To Reproduce
It's hard to reproduce. The omitted are:
Issue: https://github.com/AbsaOSS/atum-service/issues/97
PR: https://github.com/AbsaOSS/atum-service/pull/182

## Expected behavior
Figuring out what has happened, why were the tickets omitted. Was it by mistake or by some justified reason?

**Comment by miroslavpojer** [comment]
Closed with Release v0.3.0.
