### ISSUE TITLE
skip-release-notes should allow multiple entires

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/generate-release-notes#45]
## Background
`skip-release-notes` setting of the action allows to mar Issues that the contributors don't want to have release notes for.
But one value is not enough. It's enough for explicit setting, but it would be convenient to add whole groups of issues. Like _questions_ or _releases_, which usually have their own labels. 

## Feature
Allow `skip-release-notes` to accept a set of values, not just one.

**Comment by miroslavpojer** [comment]
This is related newly only for GH workflow - to disable GH check.
