### ISSUE TITLE
Previous release tag check orders by date

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/generate-release-notes#87]
## Describe the bug
This is not a _Release note generator_ bug exactly. But present in the example usage.
When checking the tag for release version the previous tags are ordered by date, not by the version number. This causes problems when a bugfix of earlier but still supported version is release after the latest actual version.
The code causing it can be found [here](https://github.com/AbsaOSS/generate-release-notes/blob/d5c5b70a174f187b5ee75479a0696be5fbbd1246/.github/workflows/release_draft.yml#L65).

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Release version 1.0.0
2. Release version 1.1.0
3. Release version 1.0.1
4. Try to release version 1.2,0
5. See error

## Expected behavior
The highest version is taken into consideration, not the latest.

**Comment by miroslavpojer** [comment]
This behavior will be fixed in issue ##119, where it can be defined from which tag the logic will collect information.
