### ISSUE TITLE
Placeholder {number} does not # before Issue or PR number

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/generate-release-notes#91]
## Describe the bug
When placing placeholders for pull requests, they are provided with # as GH works with them, like with links.
This is missing for a number with the same meaning, but the # character must be added as part of the row format.

Note: this bug is related to latest changes which are not part of master.

**Comment by benedeki** [comment]
On a second thought, do you create it as a usual markdown link, or rely on GitHub's interpretation of hash(#)?

**Comment by miroslavpojer** [comment]
> On a second thought, do you create it as a usual markdown link, or rely on GitHub's interpretation of hash(#)?

Here, it is GitHub related. So not markdown link.
